[build]
  command = "gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Clacks-Overhead         = "GNU Terry Pratchett"
    X-UA-Compatible           = "IE=edge"
    X-Frame-Options           = "SAMEORIGIN"
    X-Content-Type-Options    = "nosniff"
